services:
  - type: web
    name: talentscout
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This will be set manually in Render dashboard
    autoDeploy: true 